### PR TITLE
upgrade wdio to v7

### PR DESCRIPTION
**Pull request by taymoork2**

### CODE REVIEW

**Review by lalli-flores — CHANGES_REQUESTED** [review]
All smoke tests seem to be failing now

**Comment by taymoork2** [comment]
AWS will be fixed when this is merged in because it's node version needs to be updated

**Review by jonniespratley — APPROVED** [review]
👍

**Review by lalli-flores — APPROVED** [review]
Thanks @taymoork2 for upgrading us 🙏🏼  🙌🏼

**Pull request merged**
