### PR TITLE
fix(ActivityShare): accessibility for download buttons

### PR DESCRIPTION
**Pull request by mkesavan13**
### This pull request addresses
This PR addresses the issue of download buttons not being accessible. The download buttons can be accessed through `Shift + Tab` but the image files' Download button was not accessible.

### by making the following changes
- To fix it, we have disabled the `hover` ability of the Image component rather show the file name and downlaod button by default. This makes the download button present to be accessible by doing `Shift + Tab`
- Additionally, I've added the file names along with the download button's aria-label so that it doesn't simply read Download but rather what to download.

### Screen recording

https://github.com/user-attachments/assets/bcbca58d-c9a1-4d6b-8142-36254226edba

### CODE REVIEW

**Review by Kesari3008 — APPROVED** [review]
Why does it say dimmed while reading the aria-label and what does it mean?
Did we check if updating the css for md_content is not impacting any other element?

**Review by adhmenon — APPROVED** [review]
Overall LGTM. That 'dimmed' issue while reading the aria label is mostly due to the fact that the button is disabled.

**Comment by mkesavan13** [comment]
@adhmenon @Kesari3008 - Thanks for the approvals.

I think the `dimmed` readout is because this is a light-themed Widget. The button isn't disabled. I'll go ahead and merge the PR once the checks pass

**Comment by mkesavan13** [comment]
> Why does it say dimmed while reading the aria-label and what does it mean? Did we check if updating the css for md_content is not impacting any other element?

@Kesari3008 - For the second one, no. Since we have this CSS encapsulated under a parent CSS style that is component-specific, we do not have any other component that is affecting because of this change.

**Pull request merged**
